<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Danny Espinoza Cardenas">

<title>STAT 107 Project</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Analysis_files/libs/clipboard/clipboard.min.js"></script>
<script src="Analysis_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Analysis_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Analysis_files/libs/quarto-html/popper.min.js"></script>
<script src="Analysis_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Analysis_files/libs/quarto-html/anchor.min.js"></script>
<link href="Analysis_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Analysis_files/libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Analysis_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Analysis_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Analysis_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">STAT 107 Project</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Danny Espinoza Cardenas </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This dataset contains 21 body dimension measurements as well as age, weight, height, and gender on 507 individuals. The 247 men and 260 women were primarily individuals in their twenties and thirties, with a scattering of older men and women, all exercising several hours a week. The original dataset contains skeletal and muscular girth measurements. For this project I will be analyzing the below muscular girth measurements as well as age, weight, height, and gender. I am omitting the skeletal data because I am unable to measure my own bone structure for the purpose of my research question.</p>
<p>My research question is figuring out the statistics of where my personal muscular girth measurements would place me within a 10 year range. Comparing myself to these physically active individuals, I should be on the low tail of the data since I do no workout often. I do partake in latin dancing at least an hour or two every week and I walk my dog a minimum of 30 minutes a day, but that is probably far different than active lifestyle of individuals in the original data. That is, where does a 26-year-old lightly active male place relatively to highly active young adults of age 21 - 31 in terms of weight? I also seek to discover if my weight follows the same trend when accounting for all muscular girth measurements.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>

Table: Data Dictionary for Body Dimensions Measurement Analysis

|Variable       |Description                                                                                 |Units  |R_Type |
|:--------------|:-------------------------------------------------------------------------------------------|:------|:------|
|shoulder_girth |Shoulder girth over deltoid muscles                                                         |cm     |double |
|chest_girth    |Chest girth at nipple line in males and just above breast tissue in females, mid-expiration |cm     |double |
|waist_girth    |Waist girth, narrowest part of torso below the rib cage, (avg. of contracted/relaxed)       |cm     |double |
|navel_girth    |Abdominal girth at umbilicus using iliac crest as landmark                                  |cm     |double |
|hip_girth      |Hip girth at level of bitrochanteric diameter                                               |cm     |double |
|thigh_girth    |Thigh girth below gluteal fold, (average of right and left sides)                           |cm     |double |
|bicep_girth    |Bicep girth, flexed, (average of right and left sides)                                      |cm     |double |
|forearm_girth  |Forearm girth, extended, palm up, (average of right and left)                               |cm     |double |
|knee_girth     |Knee girth over patella, slightly flexed position, (average of right and left)              |cm     |double |
|calf_girth     |Calf maximum girth, (average of right and left)                                             |cm     |double |
|ankle_girth    |Ankle minimum girth, (average of right and left)                                            |cm     |double |
|wrist_girth    |Wrist minimum girth, (average of right and left)                                            |cm     |double |
|age            |Age                                                                                         |years  |double |
|weight         |Weight                                                                                      |kg     |double |
|height         |Height                                                                                      |cm     |double |
|gender         |Gender (0 = Female, 1 = Male)                                                               |Factor |factor |</code></pre>
</div>
</div>
</section>
<section id="methods" class="level2">
<h2 class="anchored" data-anchor-id="methods">Methods</h2>
<p>First I will look at where I land compared to three groups, Group A: 21 - 31 year old males, Group B: 21 - 31 year old females, Group C: 21 - 31 year old females and males. This will be done by comparing my position across the 3 distributions and determine my standing through z-score and percentile rankings with Group A. For Group B and C, I will be producing a table comparing the averages as they are not my main focus group for comparison.</p>
<p>First, I created a table using bind_rows() and summarise() to calculate the averages across all the columns, except gender. That table exists for simple comparison between all the three groups.</p>
<p>I then used hist() in a for loop to graph small histograms with a red abline() showcasing where my measurements land according to the distribution of each category compared to Group A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>

Table: Average Measurements (Ages 21-31)

|Group    | shoulder_girth| chest_girth| waist_girth| navel_girth| hip_girth| thigh_girth| bicep_girth| forearm_girth| knee_girth| calf_girth| ankle_girth| wrist_girth|   age| weight| height|
|:--------|--------------:|-----------:|-----------:|-----------:|---------:|-----------:|-----------:|-------------:|----------:|----------:|-----------:|-----------:|-----:|------:|------:|
|Me       |         102.20|       85.20|       79.50|       80.50|     86.30|       50.00|       31.00|         22.30|      33.00|      31.75|       20.30|       15.50| 26.00|  58.35| 175.00|
|Males    |         116.15|       99.85|       81.65|       85.12|     96.87|       56.74|       34.42|         28.34|      37.16|      37.19|       23.06|       17.15| 25.26|  77.37| 178.64|
|Females  |         100.23|       85.45|       68.95|       81.84|     94.87|       57.00|       27.75|         23.63|      35.22|      35.03|       21.27|       15.04| 25.02|  60.16| 165.85|
|Combined |         108.62|       93.04|       75.64|       83.57|     95.92|       56.87|       31.27|         26.11|      36.24|      36.17|       22.22|       16.15| 25.14|  69.23| 172.59|</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Analysis_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Next, I will check for normality before conducting my statistical inference of whether I can reject or fail to reject the hypothesis of my values being statistically lower than the average of Group A, which is the most relevant subgroup. Although visually I appear to be below the mean in most categories, I am choosing weight as an overall variable to determine if that is statistically true. This is done through a one sided t-test with hypothesis: <span class="math inline">\(H_0: \mu_{\text{weight}} = 58.35\)</span> <span class="math inline">\(H_A: \mu_{\text{weight}} &gt; 58.35\)</span></p>
<p>Finally, I will check all categories through a multivariate linear regression model to analyze if all the muscular girths to predict weight can determine if my weight truly is truly different than the trend of active individuals.</p>
</section>
<section id="results" class="level2">
<h2 class="anchored" data-anchor-id="results">Results</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  group_males$weight
t = 20.616, df = 136, p-value &lt; 2.2e-16
alternative hypothesis: true mean is greater than 58.35
95 percent confidence interval:
 75.84416      Inf
sample estimates:
mean of x 
 77.37226 </code></pre>
</div>
</div>
<p>A p-value &lt; 2.2e-16 at <span class="math inline">\(\alpha = 0.05\)</span> determines that we can reject the null hypothesis. That is, the mean weight of Group A is not 58.35 kg, but rather much higher around 77.37 kg.</p>
<p>So I am statistically far below the mean—specifically, -1.761 standard deviations away from the mean weight of active males between ages 21–31. This places me in the bottom 3.91% compared to the active males of Group A.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = weight ~ shoulder_girth + chest_girth + waist_girth + 
    navel_girth + hip_girth + thigh_girth + bicep_girth + forearm_girth + 
    knee_girth + calf_girth + ankle_girth + wrist_girth, data = group_males)

Residuals:
    Min      1Q  Median      3Q     Max 
-8.5818 -2.0979  0.3631  2.0472  8.9849 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)    -102.97328    6.44599 -15.975  &lt; 2e-16 ***
shoulder_girth    0.25300    0.08038   3.147 0.002063 ** 
chest_girth       0.12701    0.08819   1.440 0.152345    
waist_girth       0.38537    0.09488   4.062 8.58e-05 ***
navel_girth       0.07443    0.08212   0.906 0.366502    
hip_girth         0.41265    0.12130   3.402 0.000901 ***
thigh_girth       0.20880    0.15852   1.317 0.190215    
bicep_girth      -0.07772    0.22919  -0.339 0.735104    
forearm_girth     0.40980    0.39762   1.031 0.304719    
knee_girth        0.58986    0.21353   2.762 0.006613 ** 
calf_girth        0.12551    0.18927   0.663 0.508455    
ankle_girth      -0.05395    0.24946  -0.216 0.829122    
wrist_girth       0.83804    0.56421   1.485 0.139996    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 3.205 on 124 degrees of freedom
Multiple R-squared:  0.9197,    Adjusted R-squared:  0.912 
F-statistic: 118.4 on 12 and 124 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Analysis_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Analysis_files/figure-html/unnamed-chunk-4-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There is 0.912 variability accounted for by the 12 girth measurements, so this model should be a good prediction model for the weight of active males.</p>
<p>Looking at my blue data point, I follow the trendline and so although I was statistically below the average for weight, when I account for all variables I am actually inline with the group of active individuals.</p>
<p>Looking at the residual plot, my predicted weight should lie on the red trendline, but I am slightly below which means **my actual weight of 58.35 kg is less than the model’s prediction of 58.46 kg . This results in a negative residual of -0.11. This could suggest that relative to the active males, I have a lower mass density, either muscle or the unmeasured bone / skeletal density, than an average active male with my specific frame size and muscular girths.</p>
</section>
<section id="discussion" class="level2">
<h2 class="anchored" data-anchor-id="discussion">Discussion</h2>
<p>Overall, I found that while I was below the mean in all stats of muscular girth, I am actually not too different when comparing my weight compared to my overall girth measurements. Although I am slightly below, my results show that with a bit of exercise I have the ability to reach those same girths. The skeletal density due to having a smaller frame is an interesting component that I would love to get professionally measured. Which leads me to the one thing that I would do differently is get my measurements done professionally rather than using a simple tape measure and weight scale. My results are very interesting because I had always considered myself to be “skinny fat” but statistically showing that i am actually not too far off from what is deemed average is fascinating.</p>
</section>
<section id="appendix" class="level2">
<h2 class="anchored" data-anchor-id="appendix">Appendix</h2>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>